version: '3.9'

x-logging:  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "1"
    tag: "{{.Name}}"

services:
  zookeeper:
    image: apachepulsar/pulsar:4.2.0
    container_name: zookeeper
    restart: always
    command:
      - bash
      - -c
      - |
        bin/apply-config-from-env.py conf/zookeeper.conf && \
        bin/generate-zookeeper-config.sh conf/zookeeper.conf && \
        exec bin/pulsar zookeeper
    healthcheck:
      test: [ "CMD", "bin/pulsar-zookeeper-ruok.sh" ]
      interval: 10s
      timeout: 5s
      retries: 30
    logging: *default-logging
    volumes:
      - ./data/zookeeper:/pulsar/data/zookeeper
    environment:
      - metadataStoreUrl=zk:zookeeper:2181
      - PULSAR_MEM=-Xms256m -Xmx256m -XX:MaxDirectMemorySize=256m
    networks:
      - pulsar-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s

  pulsar-init:
    image: apachepulsar/pulsar:4.2.0
    container_name: pulsar-init
    hostname: pulsar-init
    command:
      - bash
      - -c
      - |
        bin/pulsar initialize-cluster-metadata \
        --cluster cluster-a \
        --zookeeper zookeeper:2181 \
        --configuration-store zookeeper:2181 \
        --web-service-url http://broker:8080 \
        --broker-service-url pulsar://broker:6650
    restart: on-failure
    logging: *default-logging
    depends_on:
      - zookeeper
    networks:
      - pulsar-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s

  bookie:
    image: apachepulsar/pulsar:4.2.0
    container_name: bookie
    command: bash -c "bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie"
    restart: on-failure
    logging: *default-logging
    depends_on:
      - zookeeper
      - pulsar-init
    environment:
      - clusterName=cluster-a
      - zkServers=zookeeper:2181
      - metadataServiceUri=metadata-store:zk:zookeeper:2181
      - advertisedAddress=bookie
      - BOOKIE_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m
    volumes:
      - ./data/bookkeeper:/pulsar/data/bookkeeper
    networks:
      - pulsar-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s

  broker:
    image: apachepulsar/pulsar:4.2.0
    container_name: broker
    hostname: broker
    restart: on-failure
    command: bash -c "bin/apply-config-from-env.py conf/broker.conf && exec bin/pulsar broker"
    logging: *default-logging
    depends_on:
      - zookeeper
      - bookie
    environment:
      - metadataStoreUrl=zk:zookeeper:2181
      - zookeeperServers=zookeeper:2181
      - clusterName=cluster-a
      - managedLedgerDefaultEnsembleSize=1
      - managedLedgerDefaultWriteQuorum=1
      - managedLedgerDefaultAckQuorum=1
      - advertisedAddress=broker
      - advertisedListeners=external:pulsar://127.0.0.1:6650
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m
    ports:
      - "6650:6650"
      - "8080:8080"
    networks:
      - pulsar-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
  
  redis:
    image: redis/redis-stack:7.2.0-v18
    container_name: redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 5
    logging: *default-logging
    volumes:
      - ./data/redis/data:/data
    ports:
      - "6379:6379"
      - "8001:8001"
      - "16379:16379"
    networks:
      - redis-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    restart: always
    command: server --address "0.0.0.0:9000" --console-address "0.0.0.0:9001" /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 30s
      retries: 5
    logging: *default-logging
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
    volumes:
      - ./data/minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minio-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: keycloak
    command:
      - start-dev
    restart: always
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:9000/health/live" ]
#      interval: 5s
#      timeout: 30s
#      retries: 5
    logging: *default-logging
    depends_on:
      - keycloak-postgres
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8090:8080"
    expose:
      - "9000"
    networks:
      - keycloak-network
      - keycloak-postgres-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s

  keycloak-postgres:
    image: postgres:18.3
    container_name: keycloak-postgres
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 30s
      retries: 5
    logging: *default-logging
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/keycloak-postgres/data:/var/lib/postgresql/18/docker
    ports:
      - "20001:5432"
    networks:
      - keycloak-postgres-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
  
  keycloak-postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: keycloak-postgres-exporter
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9187/metrics" ]
      interval: 5s
      timeout: 30s
      retries: 5
    logging: *default-logging
    depends_on:
      - keycloak-postgres
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@keycloak-postgres:5432/keycloak?sslmode=disable"
    expose:
      - "9187"
    networks:
      - keycloak-postgres-exporter-network
      - keycloak-postgres-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
  
  opentelemetry-collector-agent:
    image: otel/opentelemetry-collector-contrib:0.147.0-nightly.6d94db7
    container_name: opentelemetry-collector-agent
    command: [ "--config=/etc/otelcol-contrib/config.yaml" ]
    restart: always
#    healthcheck:
#      test: ["CMD", "wget", "--spider", "-q", "http://localhost:13133"]
#      interval: 5s
#      timeout: 30s
#      retries: 5
    logging: *default-logging
    user: "0:0"
    volumes:
      - ./otel-collector-agent-config.yaml:/etc/otelcol-contrib/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    expose:
      - "1888"
      - "8888"
      - "8889"
      - "13133"
      - "55679"
    networks:
      - opentelemetry-collector-agent-network
      - opentelemetry-collector-gateway-network
      - node-exporter-network
      - cadvisor-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
  
  opentelemetry-collector-gateway:
    image: otel/opentelemetry-collector-contrib:0.147.0-nightly.6d94db7
    container_name: opentelemetry-collector-gateway
    command: [ "--config=/etc/otelcol-contrib/config.yaml" ]
    restart: always
#    healthcheck:
#      test: ["CMD", "wget", "--spider", "-q", "http://localhost:13133"]
#      interval: 5s
#      timeout: 30s
#      retries: 5
    logging: *default-logging
    user: "0:0"
    volumes:
      - ./otel-collector-gateway-config.yaml:/etc/otelcol-contrib/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    expose:
      - "4317"
      - "4318"
      - "1888"
      - "8888"
      - "8889"
      - "13133"
      - "55679"
    networks:
      - opentelemetry-collector-gateway-network
      - prometheus-network
      - jaeger-network
      - seq-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
  
  seq:
    image: datalust/seq:2025.2.14258
    container_name: seq
    restart: always
#    healthcheck:
#      test: [ "CMD", "wget", "--spider", "-q", "http://localhost/api/health" ]
#      interval: 5s
#      timeout: 30s
#      retries: 5
    logging: *default-logging
    depends_on:
      - seq-input-gelf
    environment:
      ACCEPT_EULA: Y
      SEQ_PASSWORD: admin
    volumes:
      - ./data/seq/data:/data
    ports:
      - "8900:80"
    expose:
      - "5341"
    networks:
      - seq-network
      - seq-input-gelf-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
  
  seq-input-gelf:
    image: datalust/seq-input-gelf:3.0.458
    container_name: seq-input-gelf
    restart: always
    logging: *default-logging
    environment:
      SEQ_ADDRESS: http://seq:5341
    ports:
      - "12201:12201/udp"
    networks:
      - seq-input-gelf-network
      - seq-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
  
  jaeger:
    image: jaegertracing/all-in-one:1.71.0
    container_name: jaeger
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:14269" ]
      interval: 5s
      timeout: 30s
      retries: 5
    logging: *default-logging
    environment:
      SPAN_STORAGE_TYPE: badger
      BADGER_EPHEMERAL: "false"
      BADGER_DIRECTORY_VALUE: /badger/data
      BADGER_DIRECTORY_KEY: /badger/key
    volumes:
      - ./data/jaeger:/badger
    ports:
      - "16686:16686"
    expose:
      - "4317"
      - "4318"
      - "14269"
    networks:
      - jaeger-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
  
  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9100/metrics" ]
      interval: 5s
      timeout: 30s
      retries: 5
    logging: *default-logging
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    expose:
      - "9100"
    networks:
      - node-exporter-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/healthz" ]
      interval: 5s
      timeout: 30s
      retries: 5
    logging: *default-logging
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080"
    networks:
      - cadvisor-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
  
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    restart: always
#    healthcheck:
#      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9090/-/ready" ]
#      interval: 5s
#      timeout: 30s
#      retries: 5
    logging: *default-logging
    volumes:
      - ./data/prometheus:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - prometheus-network
      - opentelemetry-collector-gateway-network
      - pulsar-network
      - redis-network
      - minio-network
      - keycloak-network
      - keycloak-postgres-exporter-network
      - jaeger-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
  
  grafana:
    image: grafana/grafana:12.2.0-16711121739
    container_name: grafana
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health" ]
      interval: 5s
      timeout: 30s
      retries: 5
    logging: *default-logging
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SERVER_ROOT_URL: http://localhost:3000
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - prometheus-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
  
  portainer:
    image: portainer/portainer-ce:2.38.1
    container_name: portainer
    restart: always
#    healthcheck:
#      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9000/api/system/status" ]
#      interval: 5s
#      timeout: 30s
#      retries: 5
    logging: *default-logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer/data:/data
    ports:
      - "9443:9443"
      - "9442:9000"
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s

networks:
  pulsar-network:
    driver: overlay
  redis-network:
    driver: overlay
  minio-network:
    driver: overlay
  keycloak-network:
    driver: overlay
  keycloak-postgres-network:
    driver: overlay
  keycloak-postgres-exporter-network:
    driver: overlay
  selenium-hub-network:
    driver: overlay
  opentelemetry-collector-agent-network:
    driver: overlay
  opentelemetry-collector-gateway-network:
    driver: overlay
  seq-network:
    driver: overlay
  seq-input-gelf-network:
    driver: overlay
  jaeger-network:
    driver: overlay
  node-exporter-network:
    driver: overlay
  cadvisor-network:
    driver: overlay
  prometheus-network:
    driver: overlay
