worker_processes 4;

events { worker_connections 1024; }

http {
	resolver 127.0.0.11 ipv6=off;

    server {
		listen 80;

        location /health {
            access_log off;
            return 200 "healthy\n";
        }
    }
}