// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProxyServerSearcher.Persistence;

#nullable disable

namespace ProxyServerSearcher.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516060909_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Messaging.Outbox.Abstracts.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AttemptDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempt_deadline");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<int?>("AttemptsRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("attempts_remaining");

                    b.Property<JsonDocument>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("EntityState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_state");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkerId")
                        .HasColumnType("text")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("AttemptDeadline")
                        .HasDatabaseName("ix_outbox_messages_attempt_deadline");

                    b.HasIndex("Attempts")
                        .HasDatabaseName("ix_outbox_messages_attempts");

                    b.HasIndex("AttemptsRemaining")
                        .HasDatabaseName("ix_outbox_messages_attempts_remaining");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_created_at");

                    b.HasIndex("Deadline")
                        .HasDatabaseName("ix_outbox_messages_deadline");

                    b.HasIndex("EntityState")
                        .HasDatabaseName("ix_outbox_messages_entity_state");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_outbox_messages_state");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_outbox_messages_type");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_outbox_messages_updated_at");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_outbox_messages_worker_id");

                    b.HasIndex("State", "AttemptDeadline", "AttemptsRemaining", "Deadline")
                        .HasDatabaseName("ix_outbox_messages_state_attempt_deadline_attempts_remaining_d");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("ProxyServerSearcher.Domain.Entities.ProxyServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EntityState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_state");

                    b.Property<string>("HostnameOrAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hostname_or_address");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_proxy_servers");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_proxy_servers_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_proxy_servers_deleted_at");

                    b.HasIndex("EntityState")
                        .HasDatabaseName("ix_proxy_servers_entity_state");

                    b.HasIndex("HostnameOrAddress")
                        .HasDatabaseName("ix_proxy_servers_hostname_or_address");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_proxy_servers_is_deleted");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("ix_proxy_servers_normalized_name");

                    b.HasIndex("Port")
                        .HasDatabaseName("ix_proxy_servers_port");

                    b.HasIndex("Protocol")
                        .HasDatabaseName("ix_proxy_servers_protocol");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_proxy_servers_updated_at");

                    b.ToTable("proxy_servers", (string)null);
                });

            modelBuilder.Entity("ProxyServerSearcher.Domain.Entities.ProxyServerSearchStoredTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AttemptDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempt_deadline");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<int?>("AttemptsRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("attempts_remaining");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("EntityState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_state");

                    b.Property<DateTime>("PlannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkerId")
                        .HasColumnType("text")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_proxy_server_search_stored_tasks");

                    b.HasIndex("AttemptDeadline")
                        .HasDatabaseName("ix_proxy_server_search_stored_tasks_attempt_deadline");

                    b.HasIndex("Attempts")
                        .HasDatabaseName("ix_proxy_server_search_stored_tasks_attempts");

                    b.HasIndex("AttemptsRemaining")
                        .HasDatabaseName("ix_proxy_server_search_stored_tasks_attempts_remaining");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_proxy_server_search_stored_tasks_created_at");

                    b.HasIndex("Deadline")
                        .HasDatabaseName("ix_proxy_server_search_stored_tasks_deadline");

                    b.HasIndex("EntityState")
                        .HasDatabaseName("ix_proxy_server_search_stored_tasks_entity_state");

                    b.HasIndex("PlannedAt")
                        .HasDatabaseName("ix_proxy_server_search_stored_tasks_planned_at");

                    b.HasIndex("SourceName")
                        .HasDatabaseName("ix_proxy_server_search_stored_tasks_source_name");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_proxy_server_search_stored_tasks_state");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_proxy_server_search_stored_tasks_updated_at");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_proxy_server_search_stored_tasks_worker_id");

                    b.HasIndex("SourceName", "PlannedAt")
                        .IsUnique()
                        .HasDatabaseName("ix_proxy_server_search_stored_tasks_source_name_planned_at");

                    b.HasIndex("State", "AttemptDeadline", "AttemptsRemaining", "Deadline")
                        .HasDatabaseName("ix_proxy_server_search_stored_tasks_state_attempt_deadline_att");

                    b.ToTable("proxy_server_search_stored_tasks", (string)null);
                });

            modelBuilder.Entity("ProxyServerSearcher.Domain.Entities.ProxyServer", b =>
                {
                    b.OwnsOne("Messaging.Messages.ProxyServerEvents.Models.ProxyServerCredentials", "Credentials", b1 =>
                        {
                            b1.Property<Guid>("ProxyServerId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("credentials_password");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("credentials_username");

                            b1.HasKey("ProxyServerId");

                            b1.HasIndex("Password")
                                .HasDatabaseName("ix_proxy_servers_credentials_password");

                            b1.HasIndex("Username")
                                .HasDatabaseName("ix_proxy_servers_credentials_username");

                            b1.ToTable("proxy_servers");

                            b1.WithOwner()
                                .HasForeignKey("ProxyServerId")
                                .HasConstraintName("fk_proxy_servers_proxy_servers_id");
                        });

                    b.Navigation("Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
